### ISSUE TITLE
Getting affiliate links 

### ISSUE THREAD

**Issue by misterpeople** [mytja/AliExpressAPI#1]
Hey, can i get my short affiliate links with this api? I wanna build a bot.

**Comment by mytja** [comment]
Hello!
Thank you for showing interest.
Sadly, this is a `Unoffical scraping-based API for searching AliExpress`, not for gathering affiliate links using offical API.
You can check this if it is helpful:
https://stackoverflow.com/a/41079552
Thanks for understanding
